* Setup
Let LaTeX know what this is.
#+BEGIN_SRC latex
\NeedsTeXFormat{LaTeX2e}[1994/06/01]
\ProvidesClass{og-notes}[2019/04/20]
#+END_SRC
These packages help us process package options and do things like if-else statements.
#+BEGIN_SRC latex
\RequirePackage{xkeyval}
\RequirePackage{xifthen}
#+END_SRC
By default, I want section numbers in math environments such as theorems and
lemmas. But there should be an option to disable this, particularly for shorter handouts.
#+BEGIN_SRC latex
\newboolean{@og@thmsecnum}\setboolean{@og@thmsecnum}{true}
\DeclareOptionX[og]{nosec}{\setboolean{@og@thmsecnum}{false}}
#+END_SRC
#+BEGIN_SRC latex
\DeclareOptionX[og]{notoc}{\AtBeginDocument{\renewcommand{\tableofcontents}{}}}
#+END_SRC
#+BEGIN_SRC latex
\newboolean{@og@nosubsec}
\DeclareOptionX[og]{nosubsec}{\setboolean{@og@nosubsec}{true}}
#+END_SRC
#+BEGIN_SRC latex
\newboolean{@og@oneside}
\DeclareOptionX[og]{oneside}{\setboolean{@og@oneside}{true}}
#+END_SRC
#+BEGIN_SRC latex
\newboolean{@og@titlepage}
\DeclareOptionX[og]{titlepage}{\setboolean{@og@titlepage}{true}}
#+END_SRC
#+BEGIN_SRC latex
\newboolean{@og@wide}
\DeclareOptionX[og]{wide}{\setboolean{@og@wide}{true}}
#+END_SRC
#+BEGIN_SRC latex
\newboolean{@og@ref}
\DeclareOptionX[og]{ref}{\setboolean{@og@ref}{true} \RequirePackage[style=numeric]{biblatex}}
#+END_SRC
Used for formatting section headers.
#+BEGIN_SRC latex
\newboolean{@og@pset}
\DeclareOptionX[og]{pset}{
  \setboolean{@og@pset}{true}
  \setboolean{@og@nosubsec}{true}
  \setboolean{@og@thmsecnum}{false}
  \AtBeginDocument{\renewcommand{\tableofcontents}{}}
}
#+END_SRC
#+BEGIN_SRC latex
\DeclareOption*{\PassOptionsToClass{\CurrentOption}{tufte-handout}}
#+END_SRC
#+BEGIN_SRC latex
\ProcessOptionsX*[og]\relax
#+END_SRC
#+BEGIN_SRC latex
\ifthenelse{\boolean{@og@wide}}{
  \PassOptionsToPackage{letterpaper,margin=1in}{geometry}
}{
 \PassOptionsToPackage{letterpaper,left=1in,top=1in,bottom=0.9in ,headsep=2\baselineskip,textwidth=26pc,marginparsep=2pc,marginparwidth=12pc,headheight=\baselineskip}{geometry}
}
#+END_SRC
#+BEGIN_SRC latex
\ifthenelse{\boolean{@og@oneside}}{}{\PassOptionsToClass{symmetric}{tufte-handout}}
\PassOptionsToClass{nobib}{tufte-handout}
\LoadClass{tufte-handout}
#+END_SRC
** Math
What else would we use if not the AMS standard?
#+BEGIN_SRC latex
\RequirePackage{amsmath}
\RequirePackage{amssymb}
\RequirePackage{amsthm}
\RequirePackage{amsxtra}
\RequirePackage{amsfonts}
#+END_SRC
** Links
We set up =hyperref=.
#+BEGIN_SRC latex
\hypersetup{colorlinks,
  bookmarksdepth=subsection,
  citecolor=DarkGreen,
  linkcolor=Maroon,
  urlcolor=DarkBlue}
#+END_SRC
Then =cleveref=.
#+BEGIN_SRC latex
\RequirePackage{cleveref}
#+END_SRC
* Typography
This is how everything font-related works in XeTeX.
#+BEGIN_SRC latex
\RequirePackage{fontspec}
#+END_SRC
It's a clone of Palatino.
#+BEGIN_SRC latex
\RequirePackage{mathpazo}
#+END_SRC
TeX Gyre Pagella is our main font.
#+BEGIN_SRC latex
\setmainfont{texgyrepagella}[
  Extension=.otf,
  UprightFont=*-regular,
  ItalicFont=*-italic,
  BoldFont=*-bold,
  BoldItalicFont=*-bolditalic,
  Numbers={OldStyle,Proportional},
  Ligatures=TeX]
\linespread{1.05}
#+END_SRC
** Quotes
Use =csquotes=.
#+BEGIN_SRC latex
\RequirePackage{csquotes}
#+END_SRC
** Ancient Greek
This is under construction
#+BEGIN_SRC latex
% \newfontfamily\gk{GFS Porson}
% \RequirePackage{polyglossia}
% \setmainlanguage{english}
% \setotherlanguage[variant=ancient]{greek}
#+END_SRC
# The traditional approaches to writing in other languages in LaTeX involve
# something like =babel= (or =polyglossia= with XeTeX). However, the problem with
# This is that the user must explicitly switch to another language for characters
# to be rendered in it. The main other language I type in is Ancient Greek.
# Because the Greek and Latin alphabets are disjoint, we can automatically switch
# when Unicode Greek letters are in the file.
# #+BEGIN_SRC latex
# \RequirePackage[Latin,Greek]{ucharclasses}
# #+END_SRC
# My favourite Greek font is GFS Porson.
# #+BEGIN_SRC latex
# \newfontfamily\defaultfont[Ligatures=TeX,Numbers={OldStyle,Proportional}]{TeX Gyre Pagella}
# \setDefaultTransitions{\defaultfont}{}
# \newfontfamily\greekfont{GFS Porson}
# \setTransitionsForGreek{\greekfont}{}
# #+END_SRC
** Lists
#+BEGIN_SRC latex
\RequirePackage{enumitem}
\setlist[enumerate]{itemsep=1pt,topsep=3pt,leftmargin=2em}
\renewcommand{\labelenumi}{\theenumi.}
\renewcommand{\theenumii}{\alph{enumii}}
#+END_SRC
** Citations
[[https://tex.stackexchange.com/questions/238661/is-it-possible-to-fine-tune-the-citation-positions-in-tufte-biblatex-combination][This answer on StackExchange]] explains how we can move the position of a sidenote
with a citation.
#+BEGIN_SRC latex
\ifthenelse{\boolean{@og@ref}}
{\RequirePackage[style=numeric,autocite=footnote,backend=biber]{biblatex}
\usepackage{xparse}
\usepackage{xpatch}
\makeatletter
\xpatchcmd{\@footnotetext}%
{\color@begingroup}
{\color@begingroup\toggletrue{blx@footnote}}
{}
{}
\makeatother
\DeclareCiteCommand{\sidecitehelper}
{\usebibmacro{prenote}}
{\usebibmacro{citeindex}%
\usebibmacro{cite}}
{\multicitedelim}
{\usebibmacro{cite:postnote}}
\ExplSyntaxOn
\NewDocumentCommand\sidecite{D<>{}O{}om}{%
\iftoggle{blx@footnote}
{\cs_set_protected_nopar:Npn \__sct_wrapper:nn ##1 ##2 {\mkbibparens{##2}}}
{\cs_set_protected_nopar:Npn \__sct_wrapper:nn ##1 ##2 {\sidenote[][##1]{##2}}}
{\IfNoValueTF{#3}
{\__sct_wrapper:nn{#1}{\sidecitehelper[#2]{#4}}}
{\__sct_wrapper:nn{#1}{\sidecitehelper[#2][#3]{#4}}}}
}
\ExplSyntaxOff}
{}
#+END_SRC
** Theorems
We use =thmtools= to actually create the theorems and set up their counters, and
we use =mdframed= to decorate them. I do eventually want to switch to =tcolorbox=,
which seems to have cleaner syntax and much broader customisability and
functionality.
#+BEGIN_SRC latex
\RequirePackage{tikz}
\RequirePackage{thmtools}
\RequirePackage[framemethod=tikz]{mdframed}
\mdfsetup{skipabove=0.75em plus 0.25em minus 0.25em,skipbelow=0.1em minus 0.1em}
#+END_SRC
This next bit is going to be pretty ugly and repetitive, but I don't know a
better way to do it in LaTeX.

First, we define the colours.
#+BEGIN_SRC latex
\colorlet{ThmColor}{Blue}
\colorlet{PropColor}{FireBrick}
\colorlet{ExColor}{ForestGreen}
\colorlet{DefColor}{Gainsboro}
\colorlet{CorColor}{DimGrey}
\colorlet{RemColor}{Moccasin} % Dandelion
\colorlet{ConjColor}{Moccasin}
#+END_SRC
*** Theorem-esque
Borders on top and bottom.
#+BEGIN_SRC latex
\declaretheoremstyle[
headfont=\color{MediumBlue}\normalfont\scshape,
bodyfont=\normalfont\itshape,
postheadspace=0.5em,
mdframed={backgroundcolor=ThmColor!5,
linecolor=ThmColor!50,
linewidth=1pt,
leftline=false,
rightline=false,
innerrightmargin=2.25em,}]{thm}

\declaretheoremstyle[
headfont=\color{DarkRed!75}\normalfont\scshape,
bodyfont=\normalfont\itshape,
postheadspace=0.5em,
mdframed={backgroundcolor=PropColor!5,
linecolor=PropColor!40,
linewidth=1pt,
leftline=false,
rightline=false,
innerrightmargin=2.25em,}]{prop}

\declaretheoremstyle[
headfont=\normalfont\scshape,
bodyfont=\normalfont\itshape,
postheadspace=0.5em,
mdframed={backgroundcolor=CorColor!10,
linecolor=CorColor!50,
linewidth=1pt,
leftline=false,
rightline=false,
innerrightmargin=2.25em,}]{cor}
#+END_SRC
*** Definition-Esque
Bar coming out of side.
#+BEGIN_SRC latex
\declaretheoremstyle[
headfont=\color{Green}\normalfont\scshape,
postheadspace=0.5em,
mdframed={backgroundcolor=ExColor!5,
linecolor=ExColor!50,
linewidth=5pt,
topline=false,
bottomline=false,
rightline=false,
innerrightmargin=2.25em,}]{ex}

\declaretheoremstyle[
headfont=\color{DimGray}\normalfont\scshape,
postheadspace=0.5em,
mdframed={backgroundcolor=DefColor!20,
linecolor=DefColor,
linewidth=5pt,
topline=false,
bottomline=false,
rightline=false,
innerrightmargin=2.25em,}]{def}

\declaretheoremstyle[
headfont=\color{Goldenrod}\normalfont\scshape,
postheadspace=0.5em,
mdframed={backgroundcolor=RemColor!25,
linecolor=RemColor!80,
linewidth=5pt,
topline=false,
bottomline=false,
rightline=false,
innerrightmargin=2.25em,}]{rem}

\declaretheoremstyle[
headfont=\color{Goldenrod}\normalfont\scshape,
postheadspace=0.5em,
mdframed={backgroundcolor=ConjColor!25,
linecolor=ConjColor!80,
linewidth=5pt,
topline=false,
bottomline=false,
rightline=false,
innerrightmargin=2.25em,}]{conj}
#+END_SRC
*** Plain
The default style, without any colours.
#+BEGIN_SRC latex
\declaretheoremstyle[
headfont=\normalfont\scshape,
spaceabove=10pt,
spacebelow=10pt,
postheadspace=0.5em
]{plain}
#+END_SRC
*** Assigning Styles
Using =thmtools=, we actually declare theorems. First we check if we want
numbering like =Theorem 1.1= or like =Theorem 1=.
#+BEGIN_SRC latex
\ifthenelse{\boolean{@og@thmsecnum}}
{\declaretheorem[style=thm,numberwithin=section,name=theorem]{theorem}}
{\declaretheorem[style=thm,name=theorem]{theorem}}
#+END_SRC
Then we make the rest of the theorems.
#+BEGIN_SRC latex
\declaretheorem[style=prop,sibling=theorem,name=proposition]{proposition}
\declaretheorem[style=prop,unnumbered,name=proposition]{proposition*}
\declaretheorem[style=prop,sibling=theorem,name=lemma]{lemma}
\declaretheorem[style=prop,unnumbered,name=lemma]{lemma*}
\declaretheorem[style=cor,sibling=theorem,name=corollary]{corollary}
\declaretheorem[style=cor,unnumbered,name=corollary]{corollary*}
\declaretheorem[style=cor,sibling=theorem,name=claim]{claim}
\declaretheorem[style=rem,sibling=theorem,name=conjecture]{conjecture}
\declaretheorem[style=rem,sibling=theorem,name=remark]{remark}
\declaretheorem[style=rem,sibling=theorem,name=fact]{fact}
\declaretheorem[style=def,sibling=theorem,name=definition]{definition}
\declaretheorem[style=ex,sibling=theorem,name=example]{ex}
\declaretheorem[style=plain,sibling=theorem]{exercise}
\declaretheorem[style=plain]{problem}
#+END_SRC
* Page Layout
** Fullwidth for Wide Layouts
Naturally, if we aren't using a 1.5 column layout, then the =fullwidth=
environment should not do anything.
#+BEGIN_SRC latex
\ifthenelse{\boolean{@og@wide}}{\renewenvironment{fullwidth}{}{}}{}
#+END_SRC
** Title Block
If you're using this for personal use, change this to your name.
#+BEGIN_SRC latex
\makeatletter
\gdef\@author{Gautam Manohar}
#+END_SRC
I want a title centred across the whole page.
#+BEGIN_SRC latex
\ifthenelse{\boolean{@og@titlepage}}
{\newcommand*{\@course}{Course}
  \newcommand*{\course}[1]{\gdef\@course{#1}}
  \renewcommand{\maketitle}{}
  \AtBeginDocument{%
    \newgeometry{letterpaper,left=1in,top=1in,bottom=0.9in}
    \begin{titlepage}
      \raggedleft
      \rule{1pt}{\textheight}
      \hspace{0.05\textwidth}
      \parbox[b]{0.75\textwidth}{
        {\Huge\bfseries \@title}\\[1.5\baselineskip]
        {\large\itshape \@course}\\[9\baselineskip]
        {\Large\scshape \@author}\\
        \vspace{0.42\textheight}
        {\noindent \@date}\\[1\baselineskip]}
    \end{titlepage}
  \ifthenelse{\boolean{@og@wide}}{\baselineskip}{
 \newgeometry{letterpaper,left=1in,top=1in,bottom=0.9in ,headsep=2\baselineskip,textwidth=26pc,marginparsep=2pc,marginparwidth=12pc,headheight=\baselineskip}}}}
{\renewcommand{\maketitle}{%
    \begin{fullwidth}
      \centering
      {\LARGE\MakeUppercase{\so{\@title}}}\par
      \vspace{0.1\baselineskip}
      \large\scshape\MakeLowercase{\@author}\par
      \vspace{0.1\baselineskip}
      \large\scshape\MakeLowercase{\@date}\par
    \end{fullwidth}
    \vspace{\baselineskip}
    \thispagestyle{empty}}}
\makeatother
#+END_SRC
** Table of Contents
This format is inspired by =classicthesis=.
#+BEGIN_SRC latex
\makeatletter
\renewcommand\tableofcontents{%
    \section*{\contentsname
        \@mkboth{%
           \MakeUppercase\contentsname}{\MakeUppercase\contentsname}}%
    \@starttoc{toc}}
\makeatother
\setcounter{tocdepth}{3}
  \titlecontents{chapter}%
    [0em] % distance from left margin
    {\begin{fullwidth}\LARGE\rmfamily\itshape} % above (global formatting of entry)
    {\hspace*{0em}\contentslabel{2em}} % before w/label (label = ``2'')
    {\hspace*{0em}} % before w/o label
    {\rmfamily\upshape\qquad\thecontentspage} % filler + page (leaders and page num)
    [\end{fullwidth}] % after
  \titlecontents{section}
    [0em] % distance from left margin
    {\large\scshape} % above (global formatting of entry)
    {\hspace*{1.5em}\contentslabel{1.5em}} % before w/label (label = ``2.6'')
    {\hspace*{1.5em}} % before w/o label
    {\rmfamily\upshape\qquad\thecontentspage} % filler + page (leaders and page num)
    [\vspace{-0.25ex}] % after
  \titlecontents{subsection}% FIXME
    [0em] % distance from left margin
    {\rmfamily} % above (global formatting of entry)
    {\hspace*{3.5em}\contentslabel{2em}} % before w/label (label = ``2.6.1'')
    {\hspace*{3.5em}} % before w/o label
    {\rmfamily\upshape\qquad\thecontentspage} % filler + page (leaders and page num)
    [\vspace{-0.25ex}] % after
#+END_SRC
** Titling
#+BEGIN_SRC latex
\titlespacing*{\chapter}{0pt}{50pt}{40pt}

\setcounter{secnumdepth}{3}
\ifthenelse{\boolean{@og@pset}}{
  \titleformat{\section}%
  [hang]% shape
  {\normalfont\Large\itshape}% format applied to label+text
  {}% label
  {0em}% horizontal separation between label and title body
  {}% before the title body
  []% after the title body
  \titlespacing*{\section}{0pt}{3.5ex plus 1ex minus .2ex}{1.5ex plus .2ex}

  \titleformat{\subsection}%
  [runin]% shape
  {\normalfont\scshape}% format applied to label+text
  {}% label
  {0em}% horizontal separation between label and title body
  {}% before the title body
  [.\hspace*{-0.5em}]% after the title body
  \titlespacing*{\subsection}{0pt}{1ex}{2.3ex}
}{
  \titleformat{\section}%
  [hang]% shape
  {\normalfont\Large\itshape}% format applied to label+text
  {\normalfont\scshape\thesection}% label
  {1em}% horizontal separation between label and title body
  {}% before the title body
  []% after the title body
  \titlespacing*{\section}{0pt}{3.5ex plus 1ex minus 1ex}{2.3ex plus 1ex}

  \titleformat{\subsection}%
  [hang]% shape
  {\normalfont\large\itshape}% format applied to label+text
  {\normalfont\scshape\thesubsection}% label
  {1em}% horizontal separation between label and title body
  {}% before the title body
  []% after the title body
  \titlespacing*{\subsection}{0pt}{3.25ex plus 1ex minus .2ex}{1.5ex plus .2ex}
}

\titleformat{\paragraph}%
[runin]% shape
{\normalfont\itshape}% format applied to label+text
{\normalfont\scshape\theparagraph}% label
{1em}% horizontal separation between label and title body
{}% before the title body
[]% after the title body
#+END_SRC
#+begin_src latex
\raggedbottom
#+end_src
** Page Header
I don't use chapters in my notes, and I want to include info about the section
and subsection in the header. Instead of attempting the dark wizardry necessary
to get this behaviour from the =\leftmark= and =\rightmark= macros, I make my own
macros for the name of the current (sub)section.
#+BEGIN_SRC latex
\let\Sectionmark\sectionmark
\def\sectionmark#1{\def\Sectionname{#1}\Sectionmark{#1}}
\let\Subsectionmark\subsectionmark
\def\subsectionmark#1{\def\Subsectionname{#1}\Subsectionmark{#1}}
#+END_SRC
I don't really have anything to put in the footer, and it looks a little weird.
#+BEGIN_SRC latex
\makeatletter
\newcommand{\Sectionname}{}
\newcommand{\Subsectionname}{}
\fancyhf{}
\ifthenelse{\boolean{@og@nosubsec}}{
  \fancyhead[LE]{\small\thepage}
  \fancyhead[RO]{\scshape\MakeLowercase{\@author}\quad\thepage}
}{
  \fancyhead[LE]{\small\thepage\quad{\itshape\Sectionname}}
  \fancyhead[RO]{\small{\itshape\thesubsection\,\,\Subsectionname}\quad\thepage}
}
\makeatother
#+END_SRC
* Extra Features
Word count macro.
#+BEGIN_SRC latex
\newcommand{\wc}[1]{\vspace{\baselineskip}\noindent{}#1 words}
#+END_SRC
** Inkscape Figures
From [[https://github.com/gillescastel/inkscape-figures][gillescastel/inkscape-figures]].
#+BEGIN_SRC latex
\RequirePackage{import}
\RequirePackage{pdfpages}
#+END_SRC
Suppress warning from including multiple PDFs generated by Inkscape on the same page
#+BEGIN_SRC latex
% \pdfsuppresswarningpagegroup=1
#+END_SRC
* End
#+BEGIN_SRC latex
\endinput
#+END_SRC
* COMMENT Options
#+PROPERTY: header-args :tangle og-notes.cls
# Local variables:
# after-save-hook: org-babel-tangle
# end:
